@extends('layouts.admin')

@section('title', 'Admin Schedule')
@section('page-title', 'Schedule Management')

@section('content')
    <div class="page-content">
        <div class="page-header">
            <h1>Schedule</h1>
            <p>Manage appointments and schedule meetings with coaches or clients.</p>
        </div>

        <div class="schedule-controls">
            <div class="schedule-nav">
                <button class="nav-btn" data-view="month">Month</button>
                <button class="nav-btn active" data-view="week">Week</button>
                <button class="nav-btn" data-view="day">Day</button>
            </div>

            <div>
                <button class="btn-primary" id="newSessionBtn">
                    <i class="fas fa-plus"></i>
                    New Session
                </button>
            </div>
        </div>

        <div class="schedule-calendar">
            <div class="calendar-header">
                <button class="calendar-nav-btn" id="prevBtn">
                    <i class="fas fa-chevron-left"></i>
                </button>
                <h2 id="calendarTitle"></h2>
                <button class="calendar-nav-btn" id="nextBtn">
                    <i class="fas fa-chevron-right"></i>
                </button>
            </div>
            <div class="calendar-week-days" id="calendarWeekDays"></div>
            <div class="calendar-grid" id="calendarGrid">
                <!-- Calendar content will be generated by JavaScript -->
            </div>
        </div>
    </div>

    <!-- New Session Modal -->
    <div class="modal-overlay" id="newSessionModal">
        <div class="modal-content">
            <form action="{{ route('admin.meetings.store') }}" method="POST" id="newSessionForm">
                @csrf
                <div class="modal-header">
                    <h3>Schedule New Meeting</h3>
                    <button type="button" class="modal-close" id="closeNewSessionModal">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="form-grid">
                        <div class="form-group">
                            <label for="target_group">Attendee Group</label>
                            {{-- START: Updated Dropdown Options --}}
                            <select id="target_group" name="audience" class="form-select" required>
                                <option value="" disabled selected>Select audience...</option>
                                <option value="all_coaches">All Coaches</option>
                                <option value="all_clients">All Clients</option>
                                <option value="all">Both Coaches and Clients</option>
                            </select>
                            {{-- END: Updated Dropdown Options --}}
                        </div>
                        <div class="form-group">
                            <label for="sessionType">Session Type / Title</label>
                            <input type="text" id="sessionType" name="mode" placeholder="e.g., Monthly Town Hall" required>
                        </div>
                        <div class="form-group full-width">
                            <label for="sessionDate">Date</label>
                            <input type="date" id="sessionDate" name="date" required>
                        </div>
                        <div class="form-group">
                            <label for="sessionStartTime">Start Time</label>
                            <input type="time" id="sessionStartTime" name="start_time" required>
                        </div>
                        <div class="form-group">
                            <label for="sessionEndTime">End Time</label>
                            <input type="time" id="sessionEndTime" name="end_time" required>
                        </div>

                        <div class="form-group full-width">
                            <label for="meetingLink">Meeting Link (Optional)</label>
                            <input type="url" id="meetingLink" name="meeting_link" placeholder="https://zoom.us/j/123...">
                        </div>

                        <div class="form-group full-width">
                            <label for="sessionNotes">Notes (Optional)</label>
                            <textarea id="sessionNotes" name="notes" rows="3" placeholder="Add any relevant notes..."></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn-secondary" id="cancelNewSession">Cancel</button>
                    <button type="submit" class="btn-primary">Schedule Meeting</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('assets/js/admin-schedule.js') }}"></script>
@endpush
