@extends('layouts.app')

@section('title', 'My Schedule')
@section('page-title', 'Schedule')

@section('content')
    <div class="page-content">
        <div class="page-header">
            <h1>Schedule</h1>
            <p>Manage your coaching sessions and appointments.</p>
        </div>

        <div class="schedule-controls">
            <div class="schedule-nav">
                <button class="nav-btn" data-view="month">Month</button>
                <button class="nav-btn active" data-view="week">Week</button>
                <button class="nav-btn" data-view="day">Day</button>
            </div>

            <div>
                <button class="btn-primary" id="newSessionBtn">
                    <i class="fas fa-plus"></i>
                    New Session
                </button>
            </div>
        </div>

        <div class="schedule-calendar">
            <div class="calendar-header">
                <button class="calendar-nav-btn" id="prevBtn">
                    <i class="fas fa-chevron-left"></i>
                </button>
                <h2 id="calendarTitle"></h2>
                <button class="calendar-nav-btn" id="nextBtn">
                    <i class="fas fa-chevron-right"></i>
                </button>
            </div>
            <div class="calendar-week-days" id="calendarWeekDays"></div>
            <div class="calendar-grid" id="calendarGrid">
                <!-- Calendar content will be generated by JavaScript -->
            </div>
        </div>
    </div>

    <!-- New Session Modal -->
    <div class="modal-overlay" id="newSessionModal">
        <div class="modal-content">
            <form action="{{ route('coach.schedule.store') }}" method="POST" id="newSessionForm">
                @csrf
                <div class="modal-header">
                    <h3>Create New Session</h3>
                    <button type="button" class="modal-close" id="closeNewSessionModal">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="form-grid">
                        <div class="form-group">
                            <label for="client">Client</label>
                            <select id="client" name="client_id" class="form-select">
                                <option>Select a client...</option>
                                @foreach($clients as $client)
                                    <option value="{{ $client->id }}">{{ $client->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="sessionType">Session Type</label>
                            <input type="text" id="sessionType" name="session_type" placeholder="e.g., Financial Review">
                        </div>
                        <div class="form-group">
                            <label for="sessionDate">Date</label>
                            <input type="date" id="sessionDate" name="session_date">
                        </div>
                        <div class="form-group">
                            <label for="sessionStartTime">Start Time</label>
                            <input type="time" id="sessionStartTime" name="session_start_time">
                        </div>
                        <div class="form-group">
                            <label for="sessionEndTime">End Time</label>
                            <input type="time" id="sessionEndTime" name="session_end_time">
                        </div>

                        <div class="form-group full-width">
                            <label for="meetingLink">Meeting Link (Optional)</label>
                            <input type="url" id="meetingLink" name="meeting_link" placeholder="https://zoom.us/j/123...">
                        </div>

                        <div class="form-group full-width">
                            <label for="sessionNotes">Notes (Optional)</label>
                            <textarea id="sessionNotes" name="session_notes" rows="3" placeholder="Add any relevant notes..."></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn-secondary" id="cancelNewSession">Cancel</button>
                    <button type="submit" class="btn-primary">Schedule Session</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('assets/js/schedule.js') }}"></script>
@endpush
